[wokwi]
version = 1
elf = ".pio/build/nodemcuv2/firmware.elf"
firmware = ".pio/build/nodemcuv2/firmware.bin"

# If you want to access your nodemcuv2's web server
[[net.forward]]
from = "localhost:8081"
to = "target:80"